/* The UI's fonts, generated by analysis/tools/fonts.py. See README.md. */
#ifndef PL_FONTS_H
#define PL_FONTS_H

#include "lvgl.h"

LV_FONT_DECLARE(pl_font_hero)   /* 64 px bold: the number   */
LV_FONT_DECLARE(pl_font_word)   /* 30 px bold: a word, a ratio suffix */
LV_FONT_DECLARE(pl_font_label)  /* 13 px medium: labels     */
LV_FONT_DECLARE(pl_font_marker) /* 11 px medium: faint markers */

#endif /* PL_FONTS_H */
